[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "voiptester"
version = "0.0.1"
description = "Trunex VoIP / PoE tester"
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
voiptester = "app.main:main"